#Makefile
#
#TODO
all: clean $(BIN)/principal
#
#COMPILACION
todos : ejercicio1 ejercicio2 ejercicio3 ejercicio4 ejercicio5 ejercicio7 ejercicio7 ejercicio8 ejercicio10 ejercicio11 ejercicio12 ejercicio13

ejercicio1 : ejercicio1.cpp 
	g++ -o ejercicio1 -g -Wall ejercicio1.cpp

ejercicio2 : ejercicio2.cpp 
	g++ -o ejercicio2 -g -Wall ejercicio2.cpp

ejercicio3 : ejercicio3.cpp 
	g++ -o ejercicio3 -g -Wall ejercicio3.cpp

ejercicio4 : ejercicio4.cpp 
	g++ -o ejercicio4 -g -Wall ejercicio4.cpp

ejercicio5 : ejercicio5.cpp 
	g++ -o ejercicio5 -g -Wall ejercicio5.cpp

ejercicio7 : ejercicio7.cpp 
	g++ -o ejercicio7 -g -Wall ejercicio7.cpp

ejercicio8 : ejercicio8.cpp 
	g++ -o ejercicio8 -g -Wall ejercicio8.cpp

ejercicio10 : ejercicio10.cpp 
	g++ -o ejercicio10 -g -Wall ejercicio10.cpp

ejercicio11 : ejercicio11.cpp 
	g++ -o ejercicio11 -g -Wall ejercicio11.cpp

ejercicio12 : ejercicio12.cpp 
	g++ -o ejercicio12 -g -Wall ejercicio12.cpp

ejercicio13 : ejercicio13.cpp 
	g++ -o ejercicio13 -g -Wall ejercicio13.cpp 



#
# ************ Limpieza ************

clean:
	@echo "Limpiando archivos objetos "
	@rm -f ./*.o
	
mrproper: clean

